# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/labuser/Desktop/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/labuser/Desktop/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files C:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ublaze.bd
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_microblaze_0_0/ublaze_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_microblaze_0_0/ublaze_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_microblaze_0_0/ublaze_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_dlmb_v10_0/ublaze_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_dlmb_v10_0/ublaze_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_ilmb_v10_0/ublaze_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_ilmb_v10_0/ublaze_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_dlmb_bram_if_cntlr_0/ublaze_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_ilmb_bram_if_cntlr_0/ublaze_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_lmb_bram_0/ublaze_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_mdm_1_0/ublaze_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_mdm_1_0/ublaze_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_clk_wiz_1_0/ublaze_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_clk_wiz_1_0/ublaze_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_clk_wiz_1_0/ublaze_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_rst_clk_wiz_1_100M_0/ublaze_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_rst_clk_wiz_1_100M_0/ublaze_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_rst_clk_wiz_1_100M_0/ublaze_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_axi_uartlite_0_0/ublaze_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_axi_uartlite_0_0/ublaze_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_axi_uartlite_0_0/ublaze_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_axi_timer_0_0/ublaze_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_axi_timer_0_0/ublaze_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_xbar_0/ublaze_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_axi_gpio_0_0/ublaze_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_axi_gpio_0_0/ublaze_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ip/ublaze_axi_gpio_0_0/ublaze_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all C:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ublaze_ooc.xdc]
set_property is_locked true [get_files C:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/ublaze.bd]

read_verilog -library xil_defaultlib C:/Users/labuser/Desktop/project_1/project_1.srcs/sources_1/bd/ublaze/hdl/ublaze_wrapper.v
read_xdc C:/Users/labuser/Desktop/project_1/project_1.srcs/constrs_1/imports/Desktop/Basys3_Master-1.xdc
set_property used_in_implementation false [get_files C:/Users/labuser/Desktop/project_1/project_1.srcs/constrs_1/imports/Desktop/Basys3_Master-1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top ublaze_wrapper -part xc7a35tcpg236-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off
write_checkpoint -noxdef ublaze_wrapper.dcp
catch { report_utilization -file ublaze_wrapper_utilization_synth.rpt -pb ublaze_wrapper_utilization_synth.pb }
