# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Vivado/Basys3_Master-1.xdc

# Block Designs: bd/SevenSegment/SevenSegment.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SevenSegment || ORIG_REF_NAME==SevenSegment}]

# IP: bd/SevenSegment/ip/SevenSegment_clk_wiz_0_1/SevenSegment_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SevenSegment_clk_wiz_0_1 || ORIG_REF_NAME==SevenSegment_clk_wiz_0_1}]

# IP: bd/SevenSegment/ip/SevenSegment_SevenSegmentDriver_0_1/SevenSegment_SevenSegmentDriver_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SevenSegment_SevenSegmentDriver_0_1 || ORIG_REF_NAME==SevenSegment_SevenSegmentDriver_0_1}]

# IP: bd/SevenSegment/ip/SevenSegment_c_counter_binary_0_3/SevenSegment_c_counter_binary_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SevenSegment_c_counter_binary_0_3 || ORIG_REF_NAME==SevenSegment_c_counter_binary_0_3}]

# IP: bd/SevenSegment/ip/SevenSegment_c_counter_binary_1_1/SevenSegment_c_counter_binary_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SevenSegment_c_counter_binary_1_1 || ORIG_REF_NAME==SevenSegment_c_counter_binary_1_1}]

# IP: bd/SevenSegment/ip/SevenSegment_c_shift_ram_0_2/SevenSegment_c_shift_ram_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SevenSegment_c_shift_ram_0_2 || ORIG_REF_NAME==SevenSegment_c_shift_ram_0_2}]

# IP: bd/SevenSegment/ip/SevenSegment_c_shift_ram_0_3/SevenSegment_c_shift_ram_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SevenSegment_c_shift_ram_0_3 || ORIG_REF_NAME==SevenSegment_c_shift_ram_0_3}]

# IP: bd/SevenSegment/ip/SevenSegment_xlconcat_0_1/SevenSegment_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SevenSegment_xlconcat_0_1 || ORIG_REF_NAME==SevenSegment_xlconcat_0_1}]

# IP: bd/SevenSegment/ip/SevenSegment_c_shift_ram_0_0/SevenSegment_c_shift_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SevenSegment_c_shift_ram_0_0 || ORIG_REF_NAME==SevenSegment_c_shift_ram_0_0}]

# IP: bd/SevenSegment/ip/SevenSegment_c_addsub_0_0/SevenSegment_c_addsub_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SevenSegment_c_addsub_0_0 || ORIG_REF_NAME==SevenSegment_c_addsub_0_0}]

# IP: bd/SevenSegment/ip/SevenSegment_c_shift_ram_2_0/SevenSegment_c_shift_ram_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SevenSegment_c_shift_ram_2_0 || ORIG_REF_NAME==SevenSegment_c_shift_ram_2_0}]

# XDC: bd/SevenSegment/ip/SevenSegment_clk_wiz_0_1/SevenSegment_clk_wiz_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SevenSegment_clk_wiz_0_1 || ORIG_REF_NAME==SevenSegment_clk_wiz_0_1}] {/inst }]/inst ]]

# XDC: bd/SevenSegment/ip/SevenSegment_clk_wiz_0_1/SevenSegment_clk_wiz_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SevenSegment_clk_wiz_0_1 || ORIG_REF_NAME==SevenSegment_clk_wiz_0_1}] {/inst }]/inst ]]

# XDC: bd/SevenSegment/ip/SevenSegment_clk_wiz_0_1/SevenSegment_clk_wiz_0_1_ooc.xdc

# XDC: bd/SevenSegment/ip/SevenSegment_c_counter_binary_0_3/SevenSegment_c_counter_binary_0_3_ooc.xdc

# XDC: bd/SevenSegment/ip/SevenSegment_c_counter_binary_1_1/SevenSegment_c_counter_binary_1_1_ooc.xdc

# XDC: bd/SevenSegment/ip/SevenSegment_c_shift_ram_0_2/SevenSegment_c_shift_ram_0_2_ooc.xdc

# XDC: bd/SevenSegment/ip/SevenSegment_c_shift_ram_0_3/SevenSegment_c_shift_ram_0_3_ooc.xdc

# XDC: bd/SevenSegment/ip/SevenSegment_c_shift_ram_0_0/SevenSegment_c_shift_ram_0_0_ooc.xdc

# XDC: bd/SevenSegment/ip/SevenSegment_c_addsub_0_0/SevenSegment_c_addsub_0_0_ooc.xdc

# XDC: bd/SevenSegment/ip/SevenSegment_c_shift_ram_2_0/SevenSegment_c_shift_ram_2_0_ooc.xdc

# XDC: bd/SevenSegment/SevenSegment_ooc.xdc
