# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/ECE_3700/Basys3_Master-1.xdc

# Block Designs: bd/ublaze/ublaze.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ublaze || ORIG_REF_NAME==ublaze}]

# IP: bd/ublaze/ip/ublaze_microblaze_0_0/ublaze_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ublaze_microblaze_0_0 || ORIG_REF_NAME==ublaze_microblaze_0_0}]

# IP: bd/ublaze/ip/ublaze_dlmb_v10_0/ublaze_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ublaze_dlmb_v10_0 || ORIG_REF_NAME==ublaze_dlmb_v10_0}]

# IP: bd/ublaze/ip/ublaze_ilmb_v10_0/ublaze_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ublaze_ilmb_v10_0 || ORIG_REF_NAME==ublaze_ilmb_v10_0}]

# IP: bd/ublaze/ip/ublaze_dlmb_bram_if_cntlr_0/ublaze_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ublaze_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==ublaze_dlmb_bram_if_cntlr_0}]

# IP: bd/ublaze/ip/ublaze_ilmb_bram_if_cntlr_0/ublaze_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ublaze_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==ublaze_ilmb_bram_if_cntlr_0}]

# IP: bd/ublaze/ip/ublaze_lmb_bram_0/ublaze_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ublaze_lmb_bram_0 || ORIG_REF_NAME==ublaze_lmb_bram_0}]

# IP: bd/ublaze/ip/ublaze_mdm_1_0/ublaze_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ublaze_mdm_1_0 || ORIG_REF_NAME==ublaze_mdm_1_0}]

# IP: bd/ublaze/ip/ublaze_clk_wiz_1_0/ublaze_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ublaze_clk_wiz_1_0 || ORIG_REF_NAME==ublaze_clk_wiz_1_0}]

# IP: bd/ublaze/ip/ublaze_rst_clk_wiz_1_100M_0/ublaze_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ublaze_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==ublaze_rst_clk_wiz_1_100M_0}]

# IP: bd/ublaze/ip/ublaze_axi_timer_0_0/ublaze_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ublaze_axi_timer_0_0 || ORIG_REF_NAME==ublaze_axi_timer_0_0}]

# IP: bd/ublaze/ip/ublaze_axi_gpio_0_0/ublaze_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ublaze_axi_gpio_0_0 || ORIG_REF_NAME==ublaze_axi_gpio_0_0}]

# IP: bd/ublaze/ip/ublaze_microblaze_0_axi_periph_0/ublaze_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ublaze_microblaze_0_axi_periph_0 || ORIG_REF_NAME==ublaze_microblaze_0_axi_periph_0}]

# IP: bd/ublaze/ip/ublaze_xbar_0/ublaze_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ublaze_xbar_0 || ORIG_REF_NAME==ublaze_xbar_0}]

# IP: bd/ublaze/ip/ublaze_axi_uartlite_0_0/ublaze_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ublaze_axi_uartlite_0_0 || ORIG_REF_NAME==ublaze_axi_uartlite_0_0}]

# XDC: bd/ublaze/ip/ublaze_microblaze_0_0/ublaze_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ublaze_microblaze_0_0 || ORIG_REF_NAME==ublaze_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ublaze/ip/ublaze_microblaze_0_0/ublaze_microblaze_0_0_ooc_debug.xdc

# XDC: bd/ublaze/ip/ublaze_microblaze_0_0/ublaze_microblaze_0_0_ooc.xdc

# XDC: bd/ublaze/ip/ublaze_dlmb_v10_0/ublaze_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ublaze_dlmb_v10_0 || ORIG_REF_NAME==ublaze_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/ublaze/ip/ublaze_dlmb_v10_0/ublaze_dlmb_v10_0_ooc.xdc

# XDC: bd/ublaze/ip/ublaze_ilmb_v10_0/ublaze_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ublaze_ilmb_v10_0 || ORIG_REF_NAME==ublaze_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/ublaze/ip/ublaze_ilmb_v10_0/ublaze_ilmb_v10_0_ooc.xdc

# XDC: bd/ublaze/ip/ublaze_dlmb_bram_if_cntlr_0/ublaze_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/ublaze/ip/ublaze_ilmb_bram_if_cntlr_0/ublaze_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/ublaze/ip/ublaze_lmb_bram_0/ublaze_lmb_bram_0_ooc.xdc

# XDC: bd/ublaze/ip/ublaze_mdm_1_0/ublaze_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ublaze_mdm_1_0 || ORIG_REF_NAME==ublaze_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/ublaze/ip/ublaze_mdm_1_0/ublaze_mdm_1_0_ooc_trace.xdc

# XDC: bd/ublaze/ip/ublaze_clk_wiz_1_0/ublaze_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ublaze_clk_wiz_1_0 || ORIG_REF_NAME==ublaze_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/ublaze/ip/ublaze_clk_wiz_1_0/ublaze_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ublaze_clk_wiz_1_0 || ORIG_REF_NAME==ublaze_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/ublaze/ip/ublaze_clk_wiz_1_0/ublaze_clk_wiz_1_0_ooc.xdc

# XDC: bd/ublaze/ip/ublaze_rst_clk_wiz_1_100M_0/ublaze_rst_clk_wiz_1_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ublaze_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==ublaze_rst_clk_wiz_1_100M_0}]

# XDC: bd/ublaze/ip/ublaze_rst_clk_wiz_1_100M_0/ublaze_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ublaze_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==ublaze_rst_clk_wiz_1_100M_0}]

# XDC: bd/ublaze/ip/ublaze_rst_clk_wiz_1_100M_0/ublaze_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/ublaze/ip/ublaze_axi_timer_0_0/ublaze_axi_timer_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ublaze_axi_timer_0_0 || ORIG_REF_NAME==ublaze_axi_timer_0_0}]

# XDC: bd/ublaze/ip/ublaze_axi_timer_0_0/ublaze_axi_timer_0_0_ooc.xdc

# XDC: bd/ublaze/ip/ublaze_axi_gpio_0_0/ublaze_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ublaze_axi_gpio_0_0 || ORIG_REF_NAME==ublaze_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ublaze/ip/ublaze_axi_gpio_0_0/ublaze_axi_gpio_0_0_ooc.xdc

# XDC: bd/ublaze/ip/ublaze_axi_gpio_0_0/ublaze_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ublaze_axi_gpio_0_0 || ORIG_REF_NAME==ublaze_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ublaze/ip/ublaze_xbar_0/ublaze_xbar_0_ooc.xdc

# XDC: bd/ublaze/ip/ublaze_axi_uartlite_0_0/ublaze_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ublaze_axi_uartlite_0_0 || ORIG_REF_NAME==ublaze_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ublaze/ip/ublaze_axi_uartlite_0_0/ublaze_axi_uartlite_0_0_ooc.xdc

# XDC: bd/ublaze/ip/ublaze_axi_uartlite_0_0/ublaze_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ublaze_axi_uartlite_0_0 || ORIG_REF_NAME==ublaze_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ublaze/ublaze_ooc.xdc
