# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir c:/ece_3700/3700-supreme-fiesta/1_embedded_processor_systems/ip_repo/edit_AXI_SevenSegmentDriver_v1_0.cache/wt [current_project]
set_property parent.project_path c:/ece_3700/3700-supreme-fiesta/1_embedded_processor_systems/ip_repo/edit_AXI_SevenSegmentDriver_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_repo_paths {
  c:/ECE_3700/3700-supreme-fiesta/1_Embedded_Processor_Systems/ip_repo/AXI_SevenSegmentDriver_1.0
  c:/ECE_3700/3700-supreme-fiesta/IP_REPO
  c:/ECE_3700/Vivado/IP_REPO/SevenSegmentDriver
} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip c:/ECE_3700/3700-supreme-fiesta/1_Embedded_Processor_Systems/ip_repo/AXI_SevenSegmentDriver_1.0/src/AXI_SevenSegmentDriver_0/AXI_SevenSegmentDriver_0.xci
set_property is_locked true [get_files c:/ECE_3700/3700-supreme-fiesta/1_Embedded_Processor_Systems/ip_repo/AXI_SevenSegmentDriver_1.0/src/AXI_SevenSegmentDriver_0/AXI_SevenSegmentDriver_0.xci]

synth_design -top AXI_SevenSegmentDriver_0 -part xc7a35tcpg236-1 -mode out_of_context
rename_ref -prefix_all AXI_SevenSegmentDriver_0_
write_checkpoint -noxdef AXI_SevenSegmentDriver_0.dcp
catch { report_utilization -file AXI_SevenSegmentDriver_0_utilization_synth.rpt -pb AXI_SevenSegmentDriver_0_utilization_synth.pb }
if { [catch {
  file copy -force c:/ece_3700/3700-supreme-fiesta/1_embedded_processor_systems/ip_repo/edit_AXI_SevenSegmentDriver_v1_0.runs/AXI_SevenSegmentDriver_0_synth_1/AXI_SevenSegmentDriver_0.dcp c:/ECE_3700/3700-supreme-fiesta/1_Embedded_Processor_Systems/ip_repo/AXI_SevenSegmentDriver_1.0/src/AXI_SevenSegmentDriver_0/AXI_SevenSegmentDriver_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub c:/ECE_3700/3700-supreme-fiesta/1_Embedded_Processor_Systems/ip_repo/AXI_SevenSegmentDriver_1.0/src/AXI_SevenSegmentDriver_0/AXI_SevenSegmentDriver_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub c:/ECE_3700/3700-supreme-fiesta/1_Embedded_Processor_Systems/ip_repo/AXI_SevenSegmentDriver_1.0/src/AXI_SevenSegmentDriver_0/AXI_SevenSegmentDriver_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim c:/ECE_3700/3700-supreme-fiesta/1_Embedded_Processor_Systems/ip_repo/AXI_SevenSegmentDriver_1.0/src/AXI_SevenSegmentDriver_0/AXI_SevenSegmentDriver_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim c:/ECE_3700/3700-supreme-fiesta/1_Embedded_Processor_Systems/ip_repo/AXI_SevenSegmentDriver_1.0/src/AXI_SevenSegmentDriver_0/AXI_SevenSegmentDriver_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir c:/ece_3700/3700-supreme-fiesta/1_embedded_processor_systems/ip_repo/edit_AXI_SevenSegmentDriver_v1_0.ip_user_files/ip/AXI_SevenSegmentDriver_0]} {
  catch { 
    file copy -force c:/ECE_3700/3700-supreme-fiesta/1_Embedded_Processor_Systems/ip_repo/AXI_SevenSegmentDriver_1.0/src/AXI_SevenSegmentDriver_0/AXI_SevenSegmentDriver_0_stub.v c:/ece_3700/3700-supreme-fiesta/1_embedded_processor_systems/ip_repo/edit_AXI_SevenSegmentDriver_v1_0.ip_user_files/ip/AXI_SevenSegmentDriver_0
  }
}

if {[file isdir c:/ece_3700/3700-supreme-fiesta/1_embedded_processor_systems/ip_repo/edit_AXI_SevenSegmentDriver_v1_0.ip_user_files/ip/AXI_SevenSegmentDriver_0]} {
  catch { 
    file copy -force c:/ECE_3700/3700-supreme-fiesta/1_Embedded_Processor_Systems/ip_repo/AXI_SevenSegmentDriver_1.0/src/AXI_SevenSegmentDriver_0/AXI_SevenSegmentDriver_0_stub.vhdl c:/ece_3700/3700-supreme-fiesta/1_embedded_processor_systems/ip_repo/edit_AXI_SevenSegmentDriver_v1_0.ip_user_files/ip/AXI_SevenSegmentDriver_0
  }
}
