# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/ECE_3700/Vivado/Lab2/1_2_SevenSegment/1_2_SevenSegment.cache/wt [current_project]
set_property parent.project_path C:/ECE_3700/Vivado/Lab2/1_2_SevenSegment/1_2_SevenSegment.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_repo_paths c:/ECE_3700/Vivado/IP_REPO [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files C:/ECE_3700/Vivado/Lab2/1_2_SevenSegment/1_2_SevenSegment.srcs/sources_1/bd/SevenSegment/SevenSegment.bd
set_property used_in_implementation false [get_files -all c:/ECE_3700/Vivado/Lab2/1_2_SevenSegment/1_2_SevenSegment.srcs/sources_1/bd/SevenSegment/ip/SevenSegment_clk_wiz_0_1/SevenSegment_clk_wiz_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/ECE_3700/Vivado/Lab2/1_2_SevenSegment/1_2_SevenSegment.srcs/sources_1/bd/SevenSegment/ip/SevenSegment_clk_wiz_0_1/SevenSegment_clk_wiz_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/ECE_3700/Vivado/Lab2/1_2_SevenSegment/1_2_SevenSegment.srcs/sources_1/bd/SevenSegment/ip/SevenSegment_clk_wiz_0_1/SevenSegment_clk_wiz_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ECE_3700/Vivado/Lab2/1_2_SevenSegment/1_2_SevenSegment.srcs/sources_1/bd/SevenSegment/ip/SevenSegment_c_counter_binary_0_3/SevenSegment_c_counter_binary_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ECE_3700/Vivado/Lab2/1_2_SevenSegment/1_2_SevenSegment.srcs/sources_1/bd/SevenSegment/ip/SevenSegment_c_counter_binary_1_1/SevenSegment_c_counter_binary_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ECE_3700/Vivado/Lab2/1_2_SevenSegment/1_2_SevenSegment.srcs/sources_1/bd/SevenSegment/ip/SevenSegment_c_shift_ram_0_2/SevenSegment_c_shift_ram_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ECE_3700/Vivado/Lab2/1_2_SevenSegment/1_2_SevenSegment.srcs/sources_1/bd/SevenSegment/ip/SevenSegment_c_shift_ram_0_3/SevenSegment_c_shift_ram_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ECE_3700/Vivado/Lab2/1_2_SevenSegment/1_2_SevenSegment.srcs/sources_1/bd/SevenSegment/ip/SevenSegment_c_shift_ram_0_0/SevenSegment_c_shift_ram_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ECE_3700/Vivado/Lab2/1_2_SevenSegment/1_2_SevenSegment.srcs/sources_1/bd/SevenSegment/ip/SevenSegment_c_addsub_0_0/SevenSegment_c_addsub_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ECE_3700/Vivado/Lab2/1_2_SevenSegment/1_2_SevenSegment.srcs/sources_1/bd/SevenSegment/ip/SevenSegment_c_shift_ram_2_0/SevenSegment_c_shift_ram_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/ECE_3700/Vivado/Lab2/1_2_SevenSegment/1_2_SevenSegment.srcs/sources_1/bd/SevenSegment/SevenSegment_ooc.xdc]
set_property is_locked true [get_files C:/ECE_3700/Vivado/Lab2/1_2_SevenSegment/1_2_SevenSegment.srcs/sources_1/bd/SevenSegment/SevenSegment.bd]

read_verilog -library xil_defaultlib C:/ECE_3700/Vivado/Lab2/1_2_SevenSegment/1_2_SevenSegment.srcs/sources_1/bd/SevenSegment/hdl/SevenSegment_wrapper.v
read_xdc C:/ECE_3700/Vivado/Basys3_Master-1.xdc
set_property used_in_implementation false [get_files C:/ECE_3700/Vivado/Basys3_Master-1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top SevenSegment_wrapper -part xc7a35tcpg236-1
write_checkpoint -noxdef SevenSegment_wrapper.dcp
catch { report_utilization -file SevenSegment_wrapper_utilization_synth.rpt -pb SevenSegment_wrapper_utilization_synth.pb }
