# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/taylor/ECE_3700/3700-supreme-fiesta/2_1_PWM_test/2_1_PWM_test.cache/wt [current_project]
set_property parent.project_path /home/taylor/ECE_3700/3700-supreme-fiesta/2_1_PWM_test/2_1_PWM_test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_repo_paths {
  /home/taylor/ECE_3700/3700-supreme-fiesta/2_1_PWM
  /home/taylor/ECE_3700/3700-supreme-fiesta/ip_repo
} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip /home/taylor/ECE_3700/3700-supreme-fiesta/2_1_PWM_test/2_1_PWM_test.srcs/sources_1/ip/pwm_0/pwm_0.xci
set_property is_locked true [get_files /home/taylor/ECE_3700/3700-supreme-fiesta/2_1_PWM_test/2_1_PWM_test.srcs/sources_1/ip/pwm_0/pwm_0.xci]

synth_design -top pwm_0 -part xc7a35tcpg236-1 -mode out_of_context
rename_ref -prefix_all pwm_0_
write_checkpoint -noxdef pwm_0.dcp
catch { report_utilization -file pwm_0_utilization_synth.rpt -pb pwm_0_utilization_synth.pb }
if { [catch {
  file copy -force /home/taylor/ECE_3700/3700-supreme-fiesta/2_1_PWM_test/2_1_PWM_test.runs/pwm_0_synth_1/pwm_0.dcp /home/taylor/ECE_3700/3700-supreme-fiesta/2_1_PWM_test/2_1_PWM_test.srcs/sources_1/ip/pwm_0/pwm_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub /home/taylor/ECE_3700/3700-supreme-fiesta/2_1_PWM_test/2_1_PWM_test.srcs/sources_1/ip/pwm_0/pwm_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub /home/taylor/ECE_3700/3700-supreme-fiesta/2_1_PWM_test/2_1_PWM_test.srcs/sources_1/ip/pwm_0/pwm_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim /home/taylor/ECE_3700/3700-supreme-fiesta/2_1_PWM_test/2_1_PWM_test.srcs/sources_1/ip/pwm_0/pwm_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim /home/taylor/ECE_3700/3700-supreme-fiesta/2_1_PWM_test/2_1_PWM_test.srcs/sources_1/ip/pwm_0/pwm_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir /home/taylor/ECE_3700/3700-supreme-fiesta/2_1_PWM_test/2_1_PWM_test.ip_user_files/ip/pwm_0]} {
  catch { 
    file copy -force /home/taylor/ECE_3700/3700-supreme-fiesta/2_1_PWM_test/2_1_PWM_test.srcs/sources_1/ip/pwm_0/pwm_0_stub.v /home/taylor/ECE_3700/3700-supreme-fiesta/2_1_PWM_test/2_1_PWM_test.ip_user_files/ip/pwm_0
  }
}

if {[file isdir /home/taylor/ECE_3700/3700-supreme-fiesta/2_1_PWM_test/2_1_PWM_test.ip_user_files/ip/pwm_0]} {
  catch { 
    file copy -force /home/taylor/ECE_3700/3700-supreme-fiesta/2_1_PWM_test/2_1_PWM_test.srcs/sources_1/ip/pwm_0/pwm_0_stub.vhdl /home/taylor/ECE_3700/3700-supreme-fiesta/2_1_PWM_test/2_1_PWM_test.ip_user_files/ip/pwm_0
  }
}
