# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/3700/Basys3_Master-1.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_SevenSegmentDriver_0_0/design_1_SevenSegmentDriver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_SevenSegmentDriver_0_0 || ORIG_REF_NAME==design_1_SevenSegmentDriver_0_0}]

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0}]

# IP: bd/design_1/ip/design_1_c_counter_binary_0_0/design_1_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_c_counter_binary_0_0 || ORIG_REF_NAME==design_1_c_counter_binary_0_0}]

# IP: bd/design_1/ip/design_1_c_counter_binary_1_0/design_1_c_counter_binary_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_c_counter_binary_1_0 || ORIG_REF_NAME==design_1_c_counter_binary_1_0}]

# IP: bd/design_1/ip/design_1_c_shift_ram_0_0/design_1_c_shift_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_c_shift_ram_0_0 || ORIG_REF_NAME==design_1_c_shift_ram_0_0}]

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0}]

# IP: bd/design_1/ip/design_1_c_shift_ram_1_0/design_1_c_shift_ram_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_c_shift_ram_1_0 || ORIG_REF_NAME==design_1_c_shift_ram_1_0}]

# IP: bd/design_1/ip/design_1_c_shift_ram_2_0/design_1_c_shift_ram_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_c_shift_ram_2_0 || ORIG_REF_NAME==design_1_c_shift_ram_2_0}]

# IP: bd/design_1/ip/design_1_c_addsub_0_0/design_1_c_addsub_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_c_addsub_0_0 || ORIG_REF_NAME==design_1_c_addsub_0_0}]

# IP: bd/design_1/ip/design_1_c_shift_ram_3_0/design_1_c_shift_ram_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_c_shift_ram_3_0 || ORIG_REF_NAME==design_1_c_shift_ram_3_0}]

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_c_counter_binary_0_0/design_1_c_counter_binary_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_c_counter_binary_1_0/design_1_c_counter_binary_1_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_c_shift_ram_0_0/design_1_c_shift_ram_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_c_shift_ram_1_0/design_1_c_shift_ram_1_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_c_shift_ram_2_0/design_1_c_shift_ram_2_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_c_addsub_0_0/design_1_c_addsub_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_c_shift_ram_3_0/design_1_c_shift_ram_3_0_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc
